navycraft.campaign=rawget(navycraft,"campaign") or {}
local C=navycraft.campaign
local modpath=core.get_modpath(core.get_current_modname())
C.presentation=dofile(modpath.."/presentation.lua")
C.notifications=dofile(modpath.."/notifications.lua")
C.career=dofile(modpath.."/career.lua")
C.crew=dofile(modpath.."/crew.lua")
C.ports=dofile(modpath.."/ports.lua")
C.factions=dofile(modpath.."/factions.lua")
C.territories=dofile(modpath.."/territories.lua")
C.fleets=dofile(modpath.."/fleets.lua")
C.missions=dofile(modpath.."/missions.lua")
C.operations=dofile(modpath.."/operations.lua")
C.markets=dofile(modpath.."/markets.lua")
C.supply=dofile(modpath.."/supply.lua")
C.shipping=dofile(modpath.."/shipping.lua")
C.resources=dofile(modpath.."/resources.lua")
C.industry=dofile(modpath.."/industry.lua")
C.classes=dofile(modpath.."/classes.lua")
C.blueprints=dofile(modpath.."/blueprints.lua")
C.equipment=dofile(modpath.."/equipment.lua")
C.logistics=dofile(modpath.."/logistics.lua")
C.maintenance=dofile(modpath.."/maintenance.lua")
C.economy=dofile(modpath.."/economy.lua")
C.ownership=dofile(modpath.."/ownership.lua")
C.insurance=dofile(modpath.."/insurance.lua")
C.salvage=dofile(modpath.."/salvage.lua")
C.capture=dofile(modpath.."/capture.lua")
C.tutorial=dofile(modpath.."/tutorial.lua")
C.hud=dofile(modpath.."/hud.lua")
C.interfaces=dofile(modpath.."/interfaces.lua")
dofile(modpath.."/nodes.lua")
dofile(modpath.."/commands.lua")

navycraft.preview.register_launch_hook(function(construct)
    C.classes.apply(construct)
    C.equipment.apply(construct)
    C.logistics.apply(construct)
    C.maintenance.apply(construct)
    C.ownership.ensure(construct)
    return true
end)
navycraft.preview.register_step_hook(function(construct,dt)
    C.classes.apply(construct)
    C.equipment.apply(construct)
    C.logistics.apply(construct)
    C.maintenance.step(construct,dt)
    C.crew.step(construct,dt)
    C.missions.step_construct(construct,dt)
end)
navycraft.preview.register_dock_hook(function(construct)
    C.missions.on_dock(construct)
    return true
end)
navycraft.preview.register_damage_hook(function(construct,removed,position,attacker,damage_type)
    if attacker and core.get_player_by_name(attacker) then C.missions.record_damage(attacker,construct,removed) end
    C.fleets.on_damage(construct,removed,position,attacker,damage_type)
end)
navycraft.preview.register_remove_hook(function(construct,reason,snapshot)
    C.ownership.on_remove(construct,reason,snapshot)
end)
core.register_globalstep(function(dt)
    C.territories.step(dt)
    C.fleets.step(dt)
    C.markets.step(dt)
    C.industry.step(dt)
    C.supply.step(dt)
    C.shipping.step(dt)
    C.ownership.step(dt)
    C.capture.step(dt)
    C.notifications.step(dt)
    C.tutorial.step(dt)
    C.hud.step(dt)
end)

core.register_on_joinplayer(function(player)
    local name=player:get_player_name();C.career.ensure(name);C.blueprints.get(name);C.presentation.get(name);C.tutorial.get(name);C.hud.rebuild(name)
    if C.career.get(name).started and not C.factions.membership(name) then C.factions.set(name,"navy","default enlistment") end
end)
core.register_on_leaveplayer(function(player)C.hud.remove(player:get_player_name())end)
core.register_on_shutdown(function()
    C.career.save();C.ports.save();C.factions.save();C.territories.save();C.fleets.save();C.missions.save();C.operations.save();C.markets.save();C.supply.save();C.shipping.save();C.resources.save();C.industry.save();C.blueprints.save();C.ownership.save();C.insurance.save();C.salvage.save();C.presentation.save();C.tutorial.save()
end)
core.log("action","[NavyCraft Campaign] Milestone 5G tutorial, HUD, station interfaces, accessibility and notifications loaded")
