// SPDX-License-Identifier: LGPL-2.1-or-later
#include "construct_interaction.h"

#include <algorithm>
#include <cmath>
#include <stdexcept>
#include <utility>

namespace navycraft {
namespace {
bool unitNormal(const Vec3d &normal) noexcept
{
    if (!std::isfinite(normal.x) || !std::isfinite(normal.y) ||
            !std::isfinite(normal.z))
        return false;
    const double length_squared = normal.x * normal.x + normal.y * normal.y +
        normal.z * normal.z;
    return std::abs(length_squared - 1.0) <= 1e-4;
}

std::optional<ConstructNodeState> copyState(
    const DynamicConstruct &construct, const LocalNodePos &position)
{
    const auto *state = construct.getNodeState(position);
    return state ? std::optional<ConstructNodeState>(*state) : std::nullopt;
}
}

ConstructInteractionResult ConstructInteractionEngine::apply(
    DynamicConstruct &construct, const ConstructInteractionRequest &request)
{
    ConstructInteractionResult result;
    if (request.construct_id != construct.id()) {
        result.message = "construct id mismatch";
        return result;
    }
    if (!std::isfinite(request.client_time) || !unitNormal(request.world_normal)) {
        result.message = "invalid construct interaction geometry";
        return result;
    }

    const ConstructNode *target = construct.getNode(request.node_position);
    switch (request.action) {
    case ConstructInteractionAction::StartDig:
    case ConstructInteractionAction::StopDig:
    case ConstructInteractionAction::Use:
    case ConstructInteractionAction::Activate:
    case ConstructInteractionAction::ReceiveFields: {
        if (!target) {
            result.message = "construct target node is missing";
            return result;
        }
        ConstructCallbackEvent event;
        event.event_id = nextEventId();
        event.request = request;
        event.node_name = target->node_name;
        queueEvent(std::move(event));
        result.accepted = true;
        result.callback_required = true;
        return result;
    }
    case ConstructInteractionAction::DigComplete:
    case ConstructInteractionAction::Place: {
        if (!target) {
            result.message = "construct target node is missing";
            return result;
        }
        ConstructCallbackEvent event;
        event.event_id = nextEventId();
        event.request = request;
        event.node_name = target->node_name;
        event.removed_node = *target;
        m_pending_mutations.emplace(event.event_id, event);
        queueEvent(std::move(event));
        result.accepted = true;
        result.callback_required = true;
        result.message = "construct mutation awaiting callback resolution";
        return result;
    }
    case ConstructInteractionAction::Timer:
        result.message = "timer actions are generated by the server";
        return result;
    }
    result.message = "unsupported construct interaction";
    return result;
}

ConstructInteractionResult ConstructInteractionEngine::resolveMutationEvent(
    DynamicConstruct &construct, const ConstructMutationResolution &resolution)
{
    ConstructInteractionResult result;
    const auto iterator = m_pending_mutations.find(resolution.event_id);
    if (iterator == m_pending_mutations.end()) {
        result.message = "construct mutation event is not pending";
        return result;
    }
    const ConstructCallbackEvent event = iterator->second;
    if (event.request.construct_id != construct.id()) {
        result.message = "construct mutation id mismatch";
        return result;
    }

    ConstructMutationRecord record;
    record.event_id = event.event_id;
    record.construct_id = construct.id();
    record.action = event.request.action;
    record.actor = event.request.actor;
    record.wielded_item_before = event.request.wielded_item;
    record.wielded_item_after = resolution.wielded_item_after;
    record.drops = resolution.drops;
    record.protected_violation = resolution.protected_violation;
    record.reason = resolution.reason;

    if (event.request.action == ConstructInteractionAction::DigComplete) {
        record.position = event.request.node_position;
        if (const auto *node = construct.getNode(record.position))
            record.before_node = *node;
        record.before_state = copyState(construct, record.position);
        if (!(record.before_node == event.removed_node)) {
            result.message = "construct dig target changed before callback resolution";
            record.reason = result.message;
        } else if (resolution.accepted && construct.removeNode(record.position)) {
            record.accepted = true;
            result.accepted = true;
            result.node_changed = true;
            result.changed_position = record.position;
            result.removed_node = record.before_node;
        } else if (!resolution.accepted) {
            result.accepted = true;
            result.message = resolution.reason.empty() ? "construct dig rejected" : resolution.reason;
        } else {
            result.message = "construct node removal failed";
            record.reason = result.message;
        }
    } else if (event.request.action == ConstructInteractionAction::Place) {
        record.position = event.request.adjacent_position;
        if (const auto *node = construct.getNode(record.position))
            record.before_node = *node;
        record.before_state = copyState(construct, record.position);
        if (!resolution.accepted) {
            result.accepted = true;
            result.message = resolution.reason.empty() ? "construct placement rejected" : resolution.reason;
        } else if (!resolution.placed_node) {
            result.message = "construct placement resolution has no node";
            record.reason = result.message;
        } else if (record.before_node && !resolution.replace_existing) {
            result.message = "construct placement position is occupied";
            record.reason = result.message;
        } else {
            construct.setNode(record.position, *resolution.placed_node);
            if (resolution.placed_state)
                construct.setNodeState(record.position, *resolution.placed_state);
            record.after_node = *resolution.placed_node;
            record.after_state = copyState(construct, record.position);
            record.accepted = true;
            result.accepted = true;
            result.node_changed = true;
            result.changed_position = record.position;
        }
    } else {
        result.message = "event is not a construct mutation";
        return result;
    }

    m_mutation_records.push_back(std::move(record));
    m_pending_mutations.erase(iterator);
    return result;
}

std::vector<ConstructCallbackEvent> ConstructInteractionEngine::stepTimers(
    DynamicConstruct &construct, double delta_seconds)
{
    std::vector<ConstructCallbackEvent> generated;
    for (const auto &timer : construct.stepNodeTimers(delta_seconds)) {
        const ConstructNode *node = construct.getNode(timer.position);
        if (!node)
            continue;
        ConstructCallbackEvent event;
        event.event_id = nextEventId();
        event.request.construct_id = construct.id();
        event.request.action = ConstructInteractionAction::Timer;
        event.request.node_position = timer.position;
        event.node_name = node->node_name;
        event.timer_elapsed = timer.elapsed;
        event.timer_timeout = timer.timeout;
        m_unresolved_timer_events.push_back(event);
        queueEvent(event);
        generated.push_back(std::move(event));
    }
    return generated;
}

std::vector<ConstructCallbackEvent> ConstructInteractionEngine::drainEvents()
{
    std::vector<ConstructCallbackEvent> result;
    result.swap(m_events);
    return result;
}

std::vector<ConstructMutationRecord> ConstructInteractionEngine::drainMutationRecords()
{
    std::vector<ConstructMutationRecord> result;
    result.swap(m_mutation_records);
    return result;
}

bool ConstructInteractionEngine::resolveTimerEvent(
    DynamicConstruct &construct, std::uint64_t event_id, bool restart,
    double timeout_override)
{
    const auto iterator = std::find_if(m_unresolved_timer_events.begin(),
        m_unresolved_timer_events.end(), [event_id](const auto &event) {
            return event.event_id == event_id;
        });
    if (iterator == m_unresolved_timer_events.end() ||
            iterator->request.construct_id != construct.id())
        return false;
    if (restart) {
        const double timeout = timeout_override > 0.0 ?
            timeout_override : iterator->timer_timeout;
        construct.startNodeTimer(iterator->request.node_position, timeout);
    }
    m_unresolved_timer_events.erase(iterator);
    return true;
}

std::size_t ConstructInteractionEngine::pendingEventCount() const noexcept
{
    return m_events.size();
}

std::size_t ConstructInteractionEngine::pendingMutationCount() const noexcept
{
    return m_pending_mutations.size();
}

void ConstructInteractionEngine::queueEvent(ConstructCallbackEvent event)
{
    m_events.push_back(std::move(event));
}

std::uint64_t ConstructInteractionEngine::nextEventId() noexcept
{
    const std::uint64_t result = m_next_event_id++;
    if (m_next_event_id == 0)
        m_next_event_id = 1;
    return result;
}

} // namespace navycraft
