title = NavyCraft Development Game
description = Moving voxel naval combat with careers, fleets, industry, ownership, onboarding and integrated station interfaces
author = Brett Martinelli / Droopystarfish
release = 10
